FROM nvidia/cuda:12.6.2-cudnn-runtime-ubuntu22.04
# FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHON_VERSION=3.12.8

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
        ffmpeg \
        build-essential \
        cmake \
        ninja-build \
        git \
        ca-certificates \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        libffi-dev \
        liblzma-dev \
        tk-dev \
        uuid-dev \
        libgdbm-dev \
        libnss3-dev \
        libncursesw5-dev \
        fonts-dejavu-core; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    wget -O /tmp/Python.tgz "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz"; \
    tar -xzf /tmp/Python.tgz -C /tmp; \
    cd /tmp/Python-${PYTHON_VERSION}; \
    ./configure --with-ensurepip=install --enable-shared; \
    make -j2; \
    make altinstall; \
    ln -sf /usr/local/bin/python3.12 /usr/bin/python3; \
    ln -sf /usr/local/bin/pip3.12 /usr/bin/pip3; \
    rm -rf /tmp/Python.tgz /tmp/Python-${PYTHON_VERSION}

RUN set -eux; \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/python3.12.conf; \
    ldconfig

WORKDIR /app

COPY requirements.txt ./
RUN python3.12 -m pip install --no-cache-dir --upgrade pip setuptools wheel \
    && python3.12 -m pip install --no-cache-dir -r requirements.txt

# ARG SHERPA_ONNX_VERSION=1.13.4

# RUN set -eux; \
#     git clone \
#         --branch "v${SHERPA_ONNX_VERSION}" \
#         --depth 1 \
#         https://github.com/k2-fsa/sherpa-onnx.git \
#         /tmp/sherpa-onnx; \
#     cd /tmp/sherpa-onnx; \
#     SHERPA_ONNX_CMAKE_ARGS=" \
#         -DCMAKE_BUILD_TYPE=Release \
#         -DBUILD_SHARED_LIBS=ON \
#         -DSHERPA_ONNX_ENABLE_GPU=ON \
#         -DSHERPA_ONNX_ENABLE_PYTHON=ON \
#         -DSHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION=ON \
#         -DSHERPA_ONNX_ENABLE_CHECK=OFF \
#         -DSHERPA_ONNX_ENABLE_TESTS=OFF \
#         -DSHERPA_ONNX_ENABLE_PORTAUDIO=OFF \
#         -DSHERPA_ONNX_ENABLE_WEBSOCKET=OFF \
#         -DSHERPA_ONNX_ENABLE_BINARY=OFF \
#         -DSHERPA_ONNX_BUILD_C_API_EXAMPLES=OFF \
#     " \
#     CMAKE_BUILD_PARALLEL_LEVEL=2 \
#         python3.12 -m pip install \
#             --verbose \
#             --no-cache-dir \
#             --no-build-isolation \
#             .; \
#     python3.12 -c "import sherpa_onnx; print('sherpa-onnx:', sherpa_onnx.__version__); print(sherpa_onnx.__file__)"; \
#     rm -rf /tmp/sherpa-onnx

COPY . .

ENV PYTHONPATH=/app
ENV LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}

EXPOSE 8000
